# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
benchmarks:
  stack-issue-benchmarks:
    dependencies:
    - base
    - stack-issue
    - criterion
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: benchmark
category: Other
description: stack-issue is a new Haskeleton package.
executables:
  stack-issue:
    dependencies:
    - base
    - stack-issue
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: executable
  second-executable:
    dependencies:
    - base
    - stack-issue
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main2.hs
    source-dirs: executable
extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
- stack.yaml
ghc-options: -Wall
github: githubuser/stack-issue
library:
  dependencies:
  - base
  source-dirs: library
license: MIT
maintainer: Author name here
name: stack-issue
synopsis: A new Haskeleton package.
tests:
  stack-issue-test-suite:
    dependencies:
    - base
    - stack-issue
    - tasty
    - tasty-hspec
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: test-suite
version: '0.0.0'
